i04 thawing plan
DiamondLightSource/mx_bluesky pull request #103
Opened 2024-06-04 16:20 UTC by DominicOram

Fixes #102

2024-06-05 06:45 UTC, callumforrester approved these changes

2024-06-05 06:45 UTC, callumforrester commented on src/mx_bluesky/i04/thawing_plan.py
> +    smargon: Smargon = inject("smargon"),  # type: ignore
Did the type checker not like this? That's worrying...
Any ideas @DiamondJoseph

2024-06-05 06:45 UTC, callumforrester commented on .vscode/settings.json
Nit: I think this is better in a separate PR

2024-06-05 07:37 UTC, DominicOram commented on src/mx_bluesky/i04/thawing_plan.py
> +    smargon: Smargon = inject("smargon"),  # type: ignore
`inject` returns a string. I thought about making an issue but I'm not sure how you could fix it cleanly.

2024-06-05 07:38 UTC, DominicOram commented on .vscode/settings.json
Yh, probably, this was me being lazy.

2024-06-05 07:42 UTC, DiamondJoseph requested changes

2024-06-05 07:42 UTC, DiamondJoseph commented on pyproject.toml
> +    "blueapi>=0.4.3-a3",
Shouldn't be required after get MsgGenerator from dodal

2024-06-05 07:42 UTC, DiamondJoseph commented on src/mx_bluesky/i04/thawing_plan.py
> +from dodal.common import inject
```suggestion
from dodal.common import MsgGenerator, inject
```

2024-06-05 07:42 UTC, DiamondJoseph commented on src/mx_bluesky/i04/thawing_plan.py
> +    smargon: Smargon = inject("smargon"),  # type: ignore
Looks like mypy is still happy with it, but Pylance in the IDE isn't. If inject gains `-> Any` it behaves again. I'll make a PR to dodal.

2024-06-06 11:55 UTC, DominicOram commented on .vscode/settings.json
On second thoughts I'm sticking by my laziness

2024-06-06 13:44 UTC, DiamondJoseph approved these changes
I think it needs __init__.py in i04?

2024-06-06 13:53 UTC, merged