Use shutter device in I24 serial plans
DiamondLightSource/mx_bluesky pull request #112
Opened 2024-06-13 15:20 UTC by noemifrisina

Closes #110 

Needs [Dodal#623](https://github.com/DiamondLightSource/dodal/pull/623)

2024-06-27 13:49 UTC, DominicOram requested changes
Great, thank you! Couple of comments in code. Additionally it would be good if we asserted that the shutter does get open/closed in some of the tests

2024-06-27 13:49 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    # Before Open, it Resets
Should: This is an implementation detail of the shutter, I don't think we care about it from the plan level. I think we can remove the comment.

2024-06-27 13:49 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    logger.debug("Open hutch shutter")
Should: Why is opening the shutter logged at debug and closing logged at info? Feels like they should be logged at the same level?

2024-06-27 14:10 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    logger.debug("Open hutch shutter")
Yeah, should both be at debug. Must have missed the other one, thanks

2024-06-28 10:16 UTC, DominicOram approved these changes
Great, thank you!

2024-06-28 10:17 UTC, merged