Use BlueAPI abort
DiamondLightSource/mx_bluesky pull request #124
Opened 2024-07-12 14:04 UTC by noemifrisina

Closes #117 

Needs [Dodal661](https://github.com/DiamondLightSource/dodal/pull/661)

2024-07-22 11:53 UTC, DominicOram requested changes
Looks like it should work. I'm not a fan of the `ABORTED` global variable. I think that you should just call `dcid.collection_complete(end_time, aborted=False)` in an `else_plan` and `dcid.collection_complete(end_time, aborted=True)` in the except plan. Ultimately we should be using a callback for ispyb and it will be handled in there, could you make an issue for this if there isn't one already?

2024-07-22 11:53 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +        caput(pv.eiger_acquire, 0)
Should: The `finally` plan will do the detector disarm, right?

2024-07-22 11:53 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    sleep(1.0)
Should: Why are we sleeping?

2024-07-22 11:53 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    yield from disarm_zebra(zebra)  # If aborted/timed out zebra still armed
Should: Doesn't `reset_zebra_when_collection_done_plan` in the `finally` plan deal with this?

2024-07-22 16:47 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    sleep(1.0)
I believe it's to allow the PVs to actually be set - since there is no wait option on this `caput`. 1s is probably quite long though, in other parts of the code when setting these PVs it's `0.5`...

2024-07-22 16:48 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    yield from disarm_zebra(zebra)  # If aborted/timed out zebra still armed
Yes, although after going through these changes I'm not entirely sure we should be disarming the zebra in that plan. Or to be more precise, it's fine as it is for the fixed target, but in the extruder the zebra is disarmed at collection end so we shouldn't need to do it unless the collection failed/was aborted

2024-07-22 16:56 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    yield from disarm_zebra(zebra)  # If aborted/timed out zebra still armed
I don't think it really costs anything to do it in both places

2024-07-29 12:08 UTC, dperl-dls approved these changes
Looks good, if we see any issues we'll fix them separately

2024-07-29 12:10 UTC, merged