Tidy up I24 serial code
DiamondLightSource/mx_bluesky pull request #16
Opened 2023-05-31 12:56 UTC by noemifrisina

- [ ] Remove unused code from `setup_beamline` 
       (small note: `modechange` seems to be the change between goniometers. As I understand it, it's supposed to control a touch screen in the hutch that is currently broken. )
- [ ] Remove any legacy code that is not used anymore
- [ ] General tidying up 
- [ ] Add a few more tests

2023-06-16 13:29 UTC, noemifrisina commented
I don't think I can safely add more tests before making bigger changes ...

2023-06-16 13:33 UTC, noemifrisina commented
For "write_headers" and "check_files" we might want to write somewhere in the collection directory as these look like they're some sort of logs - pretty much they save a copy the parameters for each collection

2023-06-16 15:59 UTC, DominicOram requested changes
Great, good to see a bit more tidying, thanks! Minor comments in code, otherwise good

2023-06-16 15:59 UTC, DominicOram commented on dls_dev_setup.sh
> +#module load python/3.10
Should: Why is this commented out? We should probably use a fixed python version here.

2023-06-16 15:59 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    args.func(args)
Should: I think these should also be under `__main__`, we don't generally want to be doing much work on import

2023-06-16 15:59 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
> +)
Should: As above, better put in `__main__`

2023-06-16 15:59 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> -        caput(pv.me14e_gp1, 5)
Should: I assume these have been removed because they're never used? In which case can we remove the `pvar` files too?

2023-06-16 15:59 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_StartUp_py3v1.py
> +        if full_fid.is_file():
Should: You changed a bit of logic here, can you cover it with a test

2023-06-16 15:59 UTC, DominicOram commented on src/mx_bluesky/I24/serial/log.py
> +def _get_logging_file_path() -> Path:
Should: This is new functionality so can we have some unit tests round it please?

2023-06-16 15:59 UTC, DominicOram commented on src/mx_bluesky/I24/serial/setup_beamline/setup_beamline.py
> +    if action == "zlayer":
Should: I think there's loads of these actions that aren't used in SSX, can you make an issue to remove them?

2023-06-21 13:33 UTC, Tom-Willemsen reviewed
I'm assuming you've run this on the beamline to check the validity of the functional changes? Or is that scheduled for a later time?

2023-06-21 13:33 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +        % (fullmap_fid.with_suffix(".full"), fullmap_path / "currentchip.full")
I know you haven't *introduced* this, but this is really bad.

Can you either:
- Create an issue to change this and any other similar `os.system` calls to use python functions instead e.g. `shutil.copy2`
- Just do that change (as far as my simple search goes, this is the only occurence)

2023-06-21 13:33 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +    with open(param_path / f"fiducial_{point}txt", "w") as f:
Shouldn't this be

```suggestion
    with open(param_path / f"fiducial_{point}.txt", "w") as f:
```

?

2023-06-21 13:33 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +        logger.warning("Unknown Command" % name)
I think we're missing a `%s` in the format string somewhere here...

2023-06-21 14:09 UTC, noemifrisina commented
> I'm assuming you've run this on the beamline to check the validity of the functional changes? Or is that scheduled for a later time?

It's scheduled for later, once the tidying up is completed and we have a way to deploy it (but before adding any bluesky to it). Since it needs a lot of changes, tidying up/ removing things has been split up in multiple PRs to avoid having a massive one.

2023-06-21 15:10 UTC, Tom-Willemsen approved these changes

2023-06-21 15:11 UTC, merged