Tidy up logging
DiamondLightSource/mx_bluesky pull request #30
Opened 2023-07-18 13:32 UTC by noemifrisina

2023-07-18 16:16 UTC, Tom-Willemsen requested changes
I may have been a little heavy-handed with the review but logging is something that is quite important for debuggability!

Feel free to grab me if any comments don't make sense or you feel the scope is creeping too much on some of these comments.

2023-07-18 16:16 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Mapping_py3v1.py
> +                logger.info("%s \n" % line)
We shouldn't need trailing newlines on logging statements...?

2023-07-18 16:16 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_StartUp_py3v1.py
> +        raise ValueError("Unknown chip_type")
Similar to a previous comment - pull out the common string and then use it in both the logging statement and the valueerror so that the valueerror has the context of which chip type was invalid.

No further comments on similar instances, please check for similar cases throughout PR.

2023-07-18 16:16 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_StartUp_py3v1.py
> +            logger.warning("%s No known path, way =  %s" % (name, way))
In most places we got rid of the `name` prefix, should we get rid of it here too?

2023-07-18 16:16 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_StartUp_py3v1.py
> +        logger.warning("Unknown location, %s" % location)
Since it'll immediately fall over on the line below if it hits this case, this should probably be `logger.error` and maybe also a `raise ValueError(...)`.

2023-07-18 16:16 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_StartUp_py3v1.py
> +    logger.info("Write file done")
Might be beneficial to add the context of _which_ file was written.

2023-07-18 16:16 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_StartUp_py3v1.py
> +            logger.info("File Already Exists\n -->%s" % timestamp_fid)
Being a bit more explicit here would be nice. Something like:

> File /some/path/to/file already exists, Writing new file as /some/other/path/to/file instead

would be more helpful to users, I think.

2023-07-18 16:16 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
> +        logger.info("Clicked X and Y %s %s" % x, y)
```suggestion
        logger.info("Clicked X and Y %s %s" % (x, y))
```

pretty sure this is required, or at least used by convention. Please check throughout PR, no further comments on similar cases.

2023-07-18 16:16 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/setup_beamline/setup_beamline.py
> +    logger.debug("\n***** Entering Beamline")
We probably don't need a leading newline.

2023-07-18 16:16 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/setup_beamline/setup_beamline.py
> +        logger.debug("Detector distance: %s" % int(float(det_dist)))
doing an implicit `str(int(float(x)))` is a bit much for my taste.

Can't we just log the detector distance as-is?

2023-07-18 16:16 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/setup_beamline/setup_beamline.py
> +    logger.warning("WARNING: Have you set beam X and Y?")
The logger will prefix this with `[WARN]` anyway so do we need the manual `WARNING: `?

2023-07-18 16:16 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/setup_beamline/setup_beamline.py
> +    logger.warning("WARNING: Have you set header info?")
Similar to above. No further comments on similar cases, please check throughout.

2023-07-19 10:54 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    logger.debug("Running %s " % name)
Thanks, this looks good. I looked for a way to reduce duplication but after a few failed attempts I just left it, I'll try this

2023-07-19 14:41 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +        logger.info("Pilatus quickshot setup: exposure time %s" % exp_time)
Not really, you're right, changing them with %d and %f which are more correct. (For some reason it does work anyway - I guess there may be some casting done in the background)

2023-07-19 15:02 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +                    logger.info(20 * "ABORTED ")
Not really an error condition, it's just logging that the user pressed the abort button. I agree it's awful and at some point the behaviour will change, but for the moment I just want some logging telling me that things were stopped on purpose by pressing abort

2023-07-19 16:15 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +    logger.info("Long wait, please be patient")
I have no idea, my best guess would be a few minutes from the one time I saw this done. However, from what I've been told this is not something a user would run, just the beamline staff once in awhile.

2023-07-19 16:18 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +    logger.info("Long wait, please be patient")
ok - if you have a good guess put that in (we can always correct it later if it's wrong), if not then feel free to leave this comment.

2023-07-19 17:17 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_StartUp_py3v1.py
> +            logger.info("File Already Exists\n -->%s" % timestamp_fid)
Fair enough. 
We found out while trying to test it that this actually does nothing when the file exists - which is why I removed the "moving old file" comment. However, it is misleading that I'm printing out the supposedly new filename so I changed that. There's a FIXME as a reminder to actually change the file name. 
As an aside, right now it's always called and checks/writes a bunch of unused files. Since it seems it the only use these files have is if the full mapping gets fixed, it's not something the users will look for. (It is in the list of things to fix and I'll need to set up a way so that this part of the code only gets called when needed)

2023-07-19 17:20 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
> +        logger.info("Clicked X and Y %s %s" % x, y)
Ah yes, definitely a typo, good spot.

2023-07-19 17:23 UTC, noemifrisina commented
> I may have been a little heavy-handed with the review but logging is something that is quite important for debuggability!
> 
> Feel free to grab me if any comments don't make sense or you feel the scope is creeping too much on some of these comments.

The point of this was to at least try to make logging a little more sensible so a lot of comments are definitely appreciated, thank you! 
I haven't fully followed a couple and tried to explain my reasoning - let me know if they don't make sense

2023-07-19 17:38 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/setup_beamline/setup_beamline.py
> +    logger.warning("WARNING: Have you set beam X and Y?")
The logger won't print the logging level on the terminal because I didn;t want to change how things were printed out too much from what they're used to. It will be in the .log file (along with timestamp and some other useful info) if something goes wrong and we need it for debugging. 

I admit I'm not super sure what to do with this particular warning message. Ideally, once deployment is tested we'll get the beam position from somewhere else (this is the very last bit of manual changes but it hasn't been changed for more than a year) and this message will be removed completely. For the moment I'm tempted to leave it with the extra "WARNING" just to make it more visible on the terminal. A second opinion is definitely welcomed!

2023-07-20 10:09 UTC, merged