Set up deployment for I24 ssx
DiamondLightSource/mx_bluesky pull request #31
Opened 2023-07-20 13:56 UTC by noemifrisina

Closes #27 and closes #29  

- Have the edm point to the correct scripts/edms
- Have a bash script to run extruder/fixed target experiment
- Set up deployment

2023-07-24 07:48 UTC, DominicOram requested changes
This looks like it should work but to call it done it needs some user facing documentation somewhere about how to run it and how to change visit etc. Also, because we have fixed paths in the EDMs it will make testing this really hard. I think https://github.com/DiamondLightSource/mx_bluesky/issues/32 would be a better solution, what do you think?

2023-07-24 07:48 UTC, DominicOram commented on src/mx_bluesky/I24/serial/run_ssx.sh
> +echo "Activate python environment before starting edm screen"
Should: This makes it sound like something the user needs to do, rather than something this script is doing. Would be better to print something like `Activating python environment...`

2023-07-24 09:42 UTC, noemifrisina commented
> This looks like it should work but to call it done it needs some user facing documentation somewhere about how to run it and how to change visit etc. Also, because we have fixed paths in the EDMs it will make testing this really hard. I think #32 would be a better solution, what do you think?


That sounds good, although I'm not sure right now how to get a placehoder location to work in the EDM - a question for controls I guess. In any case, it definitely would work better than the set up I have right now - which is a separate branch where I have the EDMs pointing somewhere locally. 

As far as documentation goes, would adding a section for serial to the wiki here work or should it go somewhere else?

2023-07-24 09:50 UTC, DominicOram commented
> > This looks like it should work but to call it done it needs some user facing documentation somewhere about how to run it and how to change visit etc. Also, because we have fixed paths in the EDMs it will make testing this really hard. I think #32 would be a better solution, what do you think?
> 
> That sounds good, although I'm not sure right now how to get a placehoder location to work in the EDM - a question for controls I guess. In any case, it definitely would work better than the set up I have right now - which is a separate branch where I have the EDMs pointing somewhere locally.
> 
> As far as documentation goes, would adding a section for serial to the wiki here work or should it go somewhere else?

I don't mean that the placeholder should work, the idea would be to never run the EDMs with the placeholder values but only the deployed ones that have the placeholders changed to dev/prod locations depending on where you deployed them. Yh, docs on here is fine

2023-07-25 09:27 UTC, DominicOram requested changes
Good start, thanks! Some comments in code. Additionally:
* Could you log a bit more in the deploy script, it wasn't clear if it passed/failed
* The paths being copied into the EDM are relative e.g. I've got `python ./src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py write_parameter_file` in one. I think we need to replace with absolute paths?
* In addition to documenting the user facing `run_serial.sh` scripts we now need to also document this deploy script, just a line or two in the wiki about how to run it and any gotchas

2023-07-25 09:27 UTC, DominicOram commented on src/mx_bluesky/I24/serial/run_serial.py
> +            "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/extruder/EX-gui-edm/DiamondExtruder-I24-py3v1.edl",
Should: This can just be a relative path now, right?

2023-07-25 09:27 UTC, DominicOram commented on src/mx_bluesky/I24/serial/run_serial.py
> +            "/dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/DiamondChipI24-py3v1.edl",
Should: As above, should be relative

2023-07-25 09:27 UTC, DominicOram commented on src/mx_bluesky/I24/serial/run_ssx.sh
> +    edm /dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/extruder/EX-gui-edm/DiamondExtruder-I24-py3v1.edl
Should: As above, paths can be relative

2023-07-25 09:27 UTC, DominicOram commented on deploy/deploy_edm_for_ssx.sh
> +base=$( dirname "$( dirname "$0" )" )
Should: This means it's deploying relative to where the script is run from, which could vary. Better to deploy from where this script lives

2023-07-25 10:14 UTC, noemifrisina commented on deploy/deploy_edm_for_ssx.sh
> +base=$( dirname "$( dirname "$0" )" )
Done

2023-07-25 12:15 UTC, DominicOram requested changes
Thanks, paths look correct in deployed version now. Some comments in code

2023-07-25 12:15 UTC, DominicOram commented on src/mx_bluesky/I24/serial/run_ssx.sh
> +    edm /dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/extruder/EX-gui-edm/DiamondExtruder-I24-py3v1.edl
Can we not do something like:
```
#!/bin/bash

# Start the edm screen relative to requested serial collection
expt_type=${1:-FT}

current=$( realpath "$( dirname "$0" )" )
cd $current
cd ../../../..

echo "Activating python environment..."
source .venv/bin/activate

shopt -s nocasematch

if [[ $expt_type == "FT" ]] || [[ $expt_type == "fixed-target" ]]
then
    echo "Starting fixed target edm screen."
    edm ./src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/DiamondChipI24-py3v1.edl
elif [[ $expt_type == "EX" ]] || [[ $expt_type == "extruder" ]]
then
    echo "Starting extruder edm screen."
    edm ./src/mx_bluesky/I24/serial/extruder/EX-gui-edm/DiamondExtruder-I24-py3v1.edl
else
    echo "No edm found for $expt_type."
fi

echo "Edm screen closed, deactivate python environment"
deactivate
```

2023-07-25 12:15 UTC, DominicOram commented on src/mx_bluesky/I24/serial/run_ssx.sh
> +    edm /dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/DiamondChipI24-py3v1.edl
Should: This opens them in an editor, presumably we want `-x` to run them?

2023-07-25 12:15 UTC, DominicOram commented on src/mx_bluesky/I24/serial/run_ssx.sh
> +    edm /dls_sw/i24/software/bluesky/mx_bluesky/src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/DiamondChipI24-py3v1.edl
Should: The paths are also using the src version of the edms, shouldn't we be running the built version from the deploy script?

2023-07-25 12:15 UTC, DominicOram commented on src/mx_bluesky/I24/serial/run_serial.py
> +            edm_path / "FT-gui/DiamondChipI24-py3v1.edl",
Should: Shouldn't we running these rather than open them in an editor?

2023-07-25 12:32 UTC, DominicOram approved these changes
Great, thank you!

2023-07-25 12:39 UTC, merged