Add a timeout to the data collection
DiamondLightSource/mx_bluesky pull request #40
Opened 2023-09-05 15:20 UTC by noemifrisina

Temporarily add a timeout to the data collection in case something goes wrong and it gets stuck. During the last testing there were a few issues that caused the data collection to fail, but the script was not getting out of the while loop and just kept going because conditions on the PVs were not met. It also could not be easily killed from the terminal.
Needs a better solution for the future but this should allow for a slightly safer testing of the deployment. 

Timeout is calculated from the number of images to be collected and the exposure time plus a constant in seconds. Probably overdoing it with the chip, but better be safe since I'm not considering the pump_repeat in it.

2023-09-06 15:51 UTC, Tom-Willemsen requested changes
Most comments as discussed in person and likely apply to both files (only commented on the first as they're very similar).

2023-09-06 15:51 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    timeout = time.time() + int(num_imgs) * float(exp_time) + 1
As discussed in person: Not sure the `+1` on the end is sufficient here given that just the sleeps in the inner loop account for `1.5`s, before you even count any time for acquisition or `caput`s or ...

2023-09-06 15:51 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +                    break
As discussed in person: needs to break out of outer loop too

2023-09-06 15:51 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    timeout = time.time() + int(num_imgs) * float(exp_time) + 1
Can you add a comment on the appropriate line in the inner loop which *actually* waits for the acquisition to complete (in a way that presumably depends on `num_imgs` and `exp_time`)?

2023-09-06 15:51 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +                    sleep(1.0)
I don't understand why this sleep would be necessary if we're aborting anyway? If it is necessary can you add a comment explaining why, if it isn't then can you remove it?

2023-09-06 15:51 UTC, Tom-Willemsen commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    timeout = time.time() + int(num_imgs) * float(exp_time) + 1
`timeout` sounds like a duration rather than an absolute time. Maybe `timeout_time` would be clearer?

2023-09-07 15:53 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +                    sleep(1.0)
This is in the list of things to ask Robin once he's back because I do not know. For that matter I also don't know why the abort button that controls that PV shouldn't be used so I'm not touching that part for now...

2023-09-08 09:55 UTC, Tom-Willemsen approved these changes
There is still some extra duplication that's been added here between the `timeout` and `abort` cases. But if you want to fix that in a later pull request that's fine.

2023-09-08 10:22 UTC, merged