I24: get the beam centre from the
DiamondLightSource/mx_bluesky pull request #55
Opened 2023-10-27 12:47 UTC by noemifrisina

Fixes #42 

Instead of using hard coded values that need to be updated manually, get the beam centre from `display.configurations` in GDA using dodal devices.
 
Link to dodal PR: [PR220](https://github.com/DiamondLightSource/dodal/pull/220)

2023-11-02 17:34 UTC, DominicOram requested changes
See comment on https://github.com/DiamondLightSource/dodal/pull/220#pullrequestreview-1710895959. I also think that the tests are testing slightly the wrong things. We don't need tests that confirm `OAVParameters` is reading the files and doing the calculations correctly, it's up to `dodal` to test that. We instead should mock out the function on `OAVParamaters` to give us a specific beam position and test that the ellipse gets drawn in the right place and the move on click gets calculated correctly.

2023-11-02 17:34 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
> +    if event == cv.EVENT_LBUTTONUP:  # cv.EVENT_LBUTTONUP is an int! (=4)
Should: What does this comment mean? I'm not sure what it adds?

2023-11-03 16:36 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
> +    if event == cv.EVENT_LBUTTONUP:  # cv.EVENT_LBUTTONUP is an int! (=4)
To the code nothing, a note from trying to test this I forgot to remove

2023-11-07 11:44 UTC, DominicOram requested changes
Nice, great to see things incrementally getting cleaner and better tested. Some comments in code.

2023-11-07 11:44 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
> +    # cap = cv.VideoCapture("http://bl24i-di-serv-01.diamond.ac.uk:8080/OAV1.mjpg.mjpg")
Should: Can you remove commented out code please?

2023-11-07 11:44 UTC, DominicOram commented on tests/I24/serial/fixed_target/test_moveonclick.py
> +    )
Should: I think it would be good to parametrize this into `(beam_pos, expected_J1, expected_J2)` and have half a dozen or so values

2023-11-08 10:47 UTC, DominicOram approved these changes
Great, thank you!

2023-11-08 10:47 UTC, merged