Use ruff as a linter
DiamondLightSource/mx_bluesky pull request #57
Opened 2023-11-01 14:03 UTC by noemifrisina

Closes #53 . 
Replace isort/flake8 in pre-commits with Ruff.

Also pin builds to 3.11 as p4p doesn't build in 3.12 (stop docs from failing)

2023-11-02 17:01 UTC, DominicOram requested changes
Great, thank you. Minor comment. Could you add https://github.com/DiamondLightSource/dodal/pull/221/commits/b980f9bf3df0e0042a650dd9d46540d12f7589ab in to this PR too so that the CI is working?

2023-11-02 17:01 UTC, DominicOram commented on docs/conf.py
>  rst_epilog = """
Could: The links to `flake8` and `isort` links here aren't needed

2023-11-03 16:01 UTC, noemifrisina commented on docs/conf.py
>  rst_epilog = """
Done

2023-11-03 16:02 UTC, noemifrisina commented
> Great, thank you. Minor comment. Could you add [DiamondLightSource/dodal@b980f9b](https://github.com/DiamondLightSource/dodal/commit/b980f9bf3df0e0042a650dd9d46540d12f7589ab) in to this PR too so that the CI is working?

Sure... I thought the fix was already on dodal main though? (I may be confusing it with another one)

2023-11-06 07:47 UTC, dperl-dls approved these changes

2023-11-07 10:16 UTC, merged