Use ophyd device to move chip stage in movetoclick
DiamondLightSource/mx_bluesky pull request #69
Opened 2023-12-07 17:09 UTC by noemifrisina

Closes #54

2024-01-16 13:59 UTC, DominicOram requested changes
Thank you, some comments in code

2024-01-16 13:59 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +            pmac.y.move(25.40, wait=True)
Should: Could we not simplify this all down to something like:
```python
if chip_type == ChipType.Oxford or chip_type == ChipType.Minichip or chip_type == ChipType.Custom:
    chip_size = 25.4
elif chip_type == ChipType.OxfordInner:
    chip_size = 24.6
else:
   logger.warning("Unknown chip_type move")
   return

def move_xy(x, y):
    pmac.x.move(x, wait=True)
    pmac.y.move(y, wait=True)

if place == Fiducials.origin:
   move_xy(0,0)
if place == Fiducials.fid1:
   move_xy(chip_size,0)
if place == Fiducials.fid2:
   move_xy(0, chip_size)
```
Or even better, put the chip size into the enum itself

2024-01-16 13:59 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +    return
Should: This return doesn't do anything?

2024-01-16 13:59 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
> +            pmac.pmac_string.set("#3J:-1000")
Must: this makes it the same as `U`, if we need to switch direction can we do both and in a new PR?

2024-01-17 11:29 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
> +            pmac.pmac_string.set("#3J:-1000")
Ah this was a typo.

2024-01-17 12:57 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +            pmac.y.move(25.40, wait=True)
Went with the enum option, felt a bit tidier

2024-01-18 13:30 UTC, DominicOram requested changes
Thanks, some more comments, sorry

2024-01-18 13:30 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +        pmac.y.move(y)
Should: The default args to `move` have `wait=True` so this is the same behaviour as before. We also probably do want to wait on them to complete at some point so we should do something like:
```python
move_status = pmac.x.move(x, wait=False)
move_status &= pmac.y.move(y, wait=False)
move_status.wait()
```

2024-01-18 13:30 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +        pmac.z.move(0.0)
Should: As above, this is still waiting for all the axes after each move as wait defaults to True

2024-01-18 13:30 UTC, DominicOram commented on tests/I24/serial/fixed_target/test_chip_manager.py
> +    fake_pmac.y.assert_has_calls([call.move(0.0)])
Should: The fact you need to set `x` and `y` here is suspicious. `autospec` will create a `MagicMock` that matches what the thing is you're mocking, which you're saying with the type hints is a PMAC but it isn't, it's actually the `i24.pmac` function. This doesn't matter because you're code isn't even using `i24.pmac`, it just uses whatever pmac is passed into `moveto`. Basically I think this all boils down to not needing the patch at all:
```python
@patch("mx_bluesky.I24.serial.fixed_target.i24ssx_Chip_Manager_py3v1.caget")
def test_moveto_oxford_origin(fake_caget: MagicMock):
    fake_pmac: PMAC = MagicMock(spec=PMAC)
    fake_caget.return_value = 0
    moveto(Fiducials.origin, fake_pmac)
    assert fake_caget.call_count == 1
    fake_pmac.x.assert_has_calls([call.move(0.0)])
    fake_pmac.y.assert_has_calls([call.move(0.0)])
```
And similar for other tests in this file.

2024-01-18 13:30 UTC, DominicOram commented on tests/I24/serial/fixed_target/test_moveonclick.py
>  def test_onMouse_gets_beam_position_and_sends_correct_str(
Should: Same as above `fake_pmac` isn't what you think it is and `i24.pmac` doesn't need patching

2024-01-19 09:46 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/ft_utils.py
> +            return 25.40
Spun into #77

2024-01-23 16:16 UTC, DominicOram requested changes
One comment, otherwise good, thanks

2024-01-23 16:16 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +        pmac.pmac_string.put("!x0y0z0", wait=True)
Should: As in https://github.com/DiamondLightSource/mx_bluesky/pull/76 this doesn't actually do the wait. Same with all the other uses in this PR.

2024-01-23 17:01 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +        pmac.pmac_string.put("!x0y0z0", wait=True)
Ah, thanks. I thought merging #76 would fix all of these but there were still a few missing. I think I fixed them all now

2024-01-23 17:25 UTC, DominicOram approved these changes
Great, ta!

2024-01-23 17:30 UTC, merged