Use Zebra device for setting up serial
DiamondLightSource/mx_bluesky pull request #78
Opened 2024-01-22 15:04 UTC by noemifrisina

Closes #10 

Needs [Dodal#299](https://github.com/DiamondLightSource/dodal/pull/299)

Use the Zebra device in dodal and add plans to set up the serial collections for I24. 
The plans reflect the functionality of the old `zebra1` function from `setup_beamline.py`.

2024-01-23 17:06 UTC, DominicOram requested changes
Thanks, some comments in code. Most importantly I want us to get a really good understanding of how the zebra configuration works and document it here. If you want more specific suggestions of what to document then I'm happy to discuss

2024-01-23 17:06 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> -            sup.zebra1("quickshot", [gate_start, gate_width])
Should: This call and the other one changed above are surrounded by a bunch of common code, can we pull them out into a function?

2024-01-23 17:06 UTC, DominicOram commented on src/mx_bluesky/I24/serial/setup_beamline/setup_beamline.py
> -    elif action == "quickshot":
Should: This whole function is never used now. Also, presumably half the pvs in `pv.py` can we remove them all please?

2024-02-05 13:07 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/setup_beamline/setup_beamline.py
> -    elif action == "quickshot":
TBD in #79

2024-02-05 13:42 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +    yield from bps.sleep(0.1)
Reason it was repeated: at some point it hang in a weird state when trying to `caput` to that PV so added a sleep and second try just in case. 

Should be removed and tested without the repetition

2024-02-08 16:25 UTC, DominicOram requested changes
Thanks, this is certainly more understandable than before but still raises a lot of questions.

2024-02-08 16:25 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +        sleep(gate_start)  # Sleep for the same length of gate_start, hard coded to 1
Should: If this needs to be the same length as the gate start set in the zebra then it should be pulled into a constant that both parts of the code use

2024-02-08 16:25 UTC, DominicOram commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +def position_compare_off(zebra: Zebra, group: str = "position_compare_off"):
Should: Sorry, this is my fault, I don't think this actually turns it off. Just sets things to 0

2024-02-08 16:25 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> -    caput(pv.zebra1_pc_disarm, 1)
Could: Why not use `reset_zebra_when_collection_done_plan` here and remove the `zebra_return_to_normal_plan` below?

2024-02-08 16:25 UTC, DominicOram commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +            small drop (~100um) for the Eiger.
Should: This isn't my understanding, when I've used the Eiger I only need a small pulse and it triggers on the rising edge?

2024-02-08 16:25 UTC, DominicOram commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +            a falling edge is detected. For this reason a sawtooth will be set to half \
Should: What do you mean by sawtooth here? I didn't think the zebra could produce sawtooths?

2024-02-08 16:25 UTC, DominicOram commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +        - The gate input is on IN3_TTL.
Should: What is IN3_TTL connected to? is that the PMAC?

2024-02-08 16:25 UTC, DominicOram commented on tests/I24/serial/setup_beamline/test_zebra_plans.py
> +    )
Nit: Would be better split into two tests I think, one for eiger and one for pilatus

2024-02-12 14:57 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +            small drop (~100um) for the Eiger.
Honestly, this is how Robin explained it, I don't know much more than this. I'd leave this question for clarification at next meeting

2024-02-20 15:15 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +            small drop (~100um) for the Eiger.
Note: should work like this for externally enabled exposure series (mode chosen for fastchip because not all the frame starts are equally spaced in time)

2024-02-21 11:40 UTC, noemifrisina commented on tests/I24/serial/setup_beamline/test_zebra_plans.py
> +    )
Done

2024-02-21 14:17 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +def get_zebra_settings_for_extruder(
Done

2024-03-05 14:05 UTC, merged