Set up blueapi
DiamondLightSource/mx_bluesky pull request #95
Opened 2024-05-15 08:43 UTC by noemifrisina

Closes #93 

- Set up blueapi config and start runner
- Make all functions into plans and add typing
- Call the plans using blueapi in the edm screens

Note. This should be a first step #45 . The blueapi worker need to be run on the control machine as gda2 for th permission issues to go away.

2024-06-03 13:12 UTC, DominicOram requested changes
Thank you! Couple of comments

2024-06-03 13:12 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    setup_logging()
Comment: It's messy we have to set this up at the start of every plan, I have put https://github.com/DiamondLightSource/blueapi/issues/494 on the i24 backlog to fix

2024-06-03 13:12 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +def run_extruder_plan(zebra: Zebra) -> MsgGenerator:
Should: I think we can just default this so we don't need to always provide it https://diamondlightsource.github.io/blueapi/main/how-to/write-plans.html#injecting-defaults. There's only one zebra we would ever do this with after all.

2024-06-03 13:12 UTC, DominicOram commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +def run_extruder_plan(zebra: Zebra) -> MsgGenerator:
I think this is probably true for most of the device arguments throughout actually

2024-06-03 13:12 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +    # Really tempted to make a wrapper ...
Yes, you do need to add it for now but I think then prioritise the blueapi issue

2024-06-03 13:12 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/DiamondChipI24-py3v1.edl
> +  0 "blueapi -c CONFIG_LOCATION controller run start_viewer '\{\"oav\":\"oav\",\"pmac\":\"pmac\"\}'"
Must: I don't think you can run this through `BlueAPI` because it has a GUI. I think you need to just keep it outside `BlueAPI` for now

2024-06-03 13:12 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_moveonclick.py
> +# start_viewer()
Must: As above, I think this needs to stay and not be in `BlueAPI`

2024-06-03 13:12 UTC, DominicOram commented on src/mx_bluesky/I24/serial/run_extruder.sh
> +fi
Should: Can we move all this into it's own script for starting the server? Then have this and `run_fixed_target` both call that script (which will eventually move to control machine)

2024-06-04 08:48 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/DiamondChipI24-py3v1.edl
> +  0 "blueapi -c CONFIG_LOCATION controller run start_viewer '\{\"oav\":\"oav\",\"pmac\":\"pmac\"\}'"
Mmm, this is actually one of the things I tested on the beamline and the GUI seemed to work fine...

2024-06-04 09:17 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/DiamondChipI24-py3v1.edl
> +  0 "blueapi -c CONFIG_LOCATION controller run start_viewer '\{\"oav\":\"oav\",\"pmac\":\"pmac\"\}'"
Edit: the GUI works fine, the issue comes when clicking on one of the `move to` buttons, which run other plans... Here `blueAPI` will fail with this error:
```
Traceback (most recent call last):
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/bin/blueapi", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/lib/python3.11/site-packages/blueapi/cli/cli.py", line 107, in wrapper
    func(*args, **kwargs)
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/lib/python3.11/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/lib/python3.11/site-packages/blueapi/cli/cli.py", line 212, in run_plan
    updated = client.update_worker_task(WorkerTask(task_id=task_id))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/lib/python3.11/site-packages/blueapi/cli/rest.py", line 90, in update_worker_task
    return self._request_and_deserialize(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dls_sw/i24/software/bluesky/mx_bluesky_testing/mx_bluesky/.venv/lib/python3.11/site-packages/blueapi/cli/rest.py", line 124, in _request_and_deserialize
    raise BlueskyRemoteError(error_message)
blueapi.cli.event_bus_client.BlueskyRemoteError: Response failed with text: {"detail":"Worker already active"},
            with error code: 409
            which corresponds to Conflict
```

2024-06-04 09:50 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/FT-gui-edm/DiamondChipI24-py3v1.edl
> +  0 "blueapi -c CONFIG_LOCATION controller run start_viewer '\{\"oav\":\"oav\",\"pmac\":\"pmac\"\}'"
The GUI won't work when it's being run by the `BlueAPI` server that's running on the control machine...

2024-06-04 15:31 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/extruder/i24ssx_Extruder_Collect_py3v2.py
> +    setup_logging()
I just linked the issue for now

2024-06-10 08:13 UTC, DominicOram requested changes
Thank you! Couple of small comments but generally good.

2024-06-10 08:13 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +    map_path: Optional[str] = None,
Should: I think this string stuff is messy. Could you either add an issue here or on `blueAPI` to think of a nicer way to do it? It may be that using https://docs.pydantic.dev/latest/api/types/#pydantic.types.FilePath will help

2024-06-10 08:13 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +    yield from bps.sleep(5)
Should: Why is this sleep here?

2024-06-10 08:36 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Manager_py3v1.py
> +    map_path: Optional[str] = None,
Opened issue here #107 . I was going to open one in `blueAPI` but since the error came from pydantic, it might be worth to first try this.

2024-06-10 11:34 UTC, DominicOram approved these changes
Great, thank you!

2024-06-10 11:35 UTC, merged