Add new zebra plan for pump probe fixed target collection with long delays
DiamondLightSource/mx_bluesky pull request #96
Opened 2024-05-16 10:19 UTC by noemifrisina

Closes #94

2024-06-03 10:21 UTC, DominicOram requested changes
Thank you, some comments in code

2024-06-03 10:21 UTC, DominicOram commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +def setup_zebra_for_fastchip_pump_probe_with_long_delays_plan(
Should: Generally, I think we can be much more clever with sharing code between here and `setup_zebra_for_fastchip_plan` whilst making the code more readable. It seems that the only difference between them is:
* Control of the shutter on `PULSE_2`
* Delay on the start of the position compare

Additionally the order of a lot of these things doesn't really matter so could we do something like pull all common stuff out into something like `trigger_detector_at_every_chip_position(start_offset...` or maybe even more clean, add start offset to `setup_zebra_for_fastchip_plan` and just call that plan in this one?

We could then add a new plan stub for `setup_zebra_to_open_shutter_at_each_position`

2024-06-03 10:21 UTC, DominicOram commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +    yield from bps.abs_set(zebra.output.out_pvs[4], PULSE2, group=group)
Should: Can we pull this TTL into a constant like we have for PILATUS/EIGER?

2024-06-03 10:21 UTC, DominicOram commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
> +            )
Could: See below for discussion on how to split up the plan, we could even then call the separate parts here e.g.
```suggestion
         start_time_offset = SHUTTER_OPENING_TIME if PumpProbeSetting.Medium1 else 0
          yield from setup_zebra_for_fastchip_plan(
              zebra,
              parameters.detector_name,
              num_gates,
              parameters.num_exposures,
              parameters.exposure_time_s,
              start_time_offset
              wait=True,
          )
        if parameters.pump_repeat == PumpProbeSetting.Medium1:
            yield from open_shutter_at_each_location(...)
```

I'm not sure if that's much cleaner or not though

2024-06-03 10:21 UTC, DominicOram commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +    yield from set_shutter_mode(zebra, "manual")
Should: Why are we setting shutter mode to manual here then automatically controlling the shutter later? That seems like a contradiction

2024-06-03 15:56 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +    yield from set_shutter_mode(zebra, "manual")
Good point. Asked Robin and he's going to test changing this tomorrow...

2024-06-03 16:01 UTC, noemifrisina commented on src/mx_bluesky/I24/serial/fixed_target/i24ssx_Chip_Collect_py3v1.py
> +            )
Well, having just one call to `setup_zebra_for_fastchip_plan` instead of the `if.. else..` does make it a bit more readable imo... 
I wonder if it would be a bit tidier to call `open_shutter_at_each_location` from the main `setup_zebra` plan instead of the collection one?

2024-06-04 14:11 UTC, DominicOram approved these changes
Thanks, I think this is a lot cleaner. Couple of comments, happy for you to merge after addressing them

2024-06-04 14:11 UTC, DominicOram commented on src/mx_bluesky/I24/serial/setup_beamline/setup_zebra_plans.py
> +def open_fast_shutter_at_each_position_plan(
Should: I think a bit of logging in this function would be good

2024-06-04 14:11 UTC, DominicOram commented on tests/I24/serial/setup_beamline/test_zebra_plans.py
> +    )
Could: I think it's cleaner to do the maths here properly i.e.
```suggestion
    expected_pulse_width = num_exp * exposure_time + 0.05 
    assert await zebra.output.pulse_2.width.get_value() == pytest.approx(
        expected_pulse_width, abs=1e-3
    )
```

2024-06-04 15:16 UTC, merged